apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-db-config
  namespace: fraud-detection
data:
  POSTGRES_DB: fraud_detection
  POSTGRES_USER: fraud_user
---
apiVersion: v1
kind: Secret
metadata:
  name: fraud-db-secret
  namespace: fraud-detection
type: Opaque
data:
  POSTGRES_PASSWORD: ZnJhdWRfcGFzcw== # fraud_pass base64 encoded
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-db
  namespace: fraud-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-db
  template:
    metadata:
      labels:
        app: fraud-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: fraud-db-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: fraud-db-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fraud-db-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-db
  namespace: fraud-detection
spec:
  selector:
    app: fraud-db
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
