apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-api-config
  namespace: fraud-detection
data:
  DATABASE_URL: "postgresql://fraud_user:fraud_pass@fraud-db:5432/fraud_detection"
  BANK_API_BASE: "http://frontend.default.svc.cluster.local:8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: fraud-api-secret
  namespace: fraud-detection
type: Opaque
data:
  GEMINI_API_KEY: QUl6YVN5QjV0WlZ3WmVISlg2R3dSRTdkdVhRUm8wSUtXalhKZG00 # GEMINI_KEY base64 encoded
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-api
  namespace: fraud-detection
  labels:
    app: fraud-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraud-api
  template:
    metadata:
      labels:
        app: fraud-api
    spec:
      containers:
        - name: fraud-api
          image: fraud-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: fraud-api-config
                  key: DATABASE_URL
            - name: BANK_API_BASE
              valueFrom:
                configMapKeyRef:
                  name: fraud-api-config
                  key: BANK_API_BASE
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: fraud-api-secret
                  key: GEMINI_API_KEY
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-api
  namespace: fraud-detection
spec:
  selector:
    app: fraud-api
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fraud-api-hpa
  namespace: fraud-detection
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fraud-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
